exclude: |
  (?x)^(
      docs/site/.*|       # Exclude mkdocs compiled files
      \.history/.*|       # Exclude history files
      .*cache.*/.*|       # Exclude cache directories
      .*venv.*/.*|        # Exclude virtual environment directories
  )$
fail_fast: true
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  # -------------------------- üîç Code Quality Tools ------------------------- #

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  # ---------------------------- ‚ö°Ô∏è uv Build Tools --------------------------- #

  # This helps ensure cross-compatibility with people who don't wish to use uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.18
    hooks:
      - id: uv-sync
        name: "‚ö°Ô∏è uv ¬∑ Sync dependencies with uv"
      - id: uv-lock
        name: "‚ö°Ô∏è uv ¬∑ Update dependency lockfile"
      - id: uv-export
        name: "‚ö°Ô∏è uv ¬∑ Export dependencies to requirements-dev.txt"
        args: ["--no-hashes", --output-file, requirements-dev.txt]

